### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by bepehr** [rkhayyat/SyrianForumFrance#1]
Hi
Your project link is in nativeScript website as RTL support example , can you provide some information about this ? how can we do it too ? i need to make my app RTL too

**Comment by rkhayyat** [comment]
Hi,

Actually, there is nothing special, Angular 2/4 took the whole job for me, they are supporting Arabic (or RTL) by default :)

**Comment by bepehr** [comment]
Can you provide more information please ? Is there any config i should enable or code  or it will enable by phone if its language is RTL ? I googled it but i got nothing , you can save my day ! :)

**Comment by rkhayyat** [comment]
Are you planning to do your app in Nativescript/Angular4 ? if that is the case then nothing to do from your side, the language support the RTL by default :), have can take a look at my repo on git, no special config I did for RTL.

Thanks for your interest.

**Comment by rkhayyat** [comment]
no more issues, issue is closed

**Comment by mid787** [comment]
@bepehr  did you find where in his code he flips(!) rtl to ltr ?

**Comment by bepehr** [comment]
Hi ,my requirement was complete control for RTL support such as force to
RTL or LTR and  i did not find any good solution so i switched back to
Android studio for developing my app but maybe my search was not enough  ,
you can search and post here if you find any good solutions.

**Comment by rnmhdn** [comment]
seems like I should switch back to AS too...
